const SYSTEM = `You are the AI Financial Concierge for Haskins & Associates, an Old Mutual Personal Financial Advice practice in South Africa. Your job is to help website visitors understand which general financial-planning area may be relevant and encourage an appropriate conversation with a financial adviser. Be warm, concise and premium. Never give personalised financial advice, investment recommendations, product recommendations, tax/legal conclusions, return forecasts, or tell a user what they should buy/sell. Do not ask for or accept ID numbers, bank/account/policy numbers, passwords, PINs, medical details, or other sensitive data. You may discuss general categories: retirement, investment/wealth planning, risk/life protection, estate planning, education planning, healthcare solutions, short-term insurance and business assurance. If the user asks for a personalised recommendation, explain that a financial adviser needs to understand their circumstances and invite them to book a consultation. Keep answers under 120 words. End with one useful next step when appropriate.`;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}})}
function clean(v,n=600){return String(v||'').trim().slice(0,n)}
function intentFor(s){s=s.toLowerCase();if(/retire|pension/.test(s))return'retirement';if(/invest|wealth|save/.test(s))return'investment';if(/life cover|protect|disability|income protection/.test(s))return'risk';if(/will|estate|legacy|death/.test(s))return'estate';if(/business|key person|buy.sell/.test(s))return'business';if(/school|education|university/.test(s))return'education';if(/medical|health/.test(s))return'health';return'general'}
const SARB_RATES_URL='https://www.resbank.co.za/en/home/what-we-do/statistics/key-statistics/selected-historical-rates';
function extractRate(source,patterns){for(const pattern of patterns){const match=source.match(pattern);if(match){const value=Number(match[1]);if(Number.isFinite(value)&&value>0&&value<100)return value}}return null}
async function officialMarketRates(){const upstream=await fetch(SARB_RATES_URL,{headers:{accept:'text/html,application/xhtml+xml','user-agent':'HaskinsAndAssociatesMarketRates/1.0'},cf:{cacheTtl:300,cacheEverything:true}});if(!upstream.ok)throw new Error('Official rate source unavailable');const html=await upstream.text();const readable=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/\s+/g,' ');const repo=extractRate(readable,[/(?:SARB\s+policy\s+rate|repurchase\s+rate|repo\s+rate)\D{0,100}(\d{1,2}(?:\.\d{1,2})?)/i]);const prime=extractRate(readable,[/(?:prime\s+lending\s+rate|prime\s+rate|\bPRIME\b)\D{0,100}(\d{1,2}(?:\.\d{1,2})?)/i]);if(repo===null||prime===null)throw new Error('Official rates could not be verified');return{repo,prime,source:SARB_RATES_URL,checkedAt:new Date().toISOString()}}
export default {async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/api/market-rates'&&request.method==='GET'){try{return json(await officialMarketRates())}catch(e){return json({error:'Current official Reserve Bank rates are unavailable'},503)}}if(u.pathname==='/api/ai'&&request.method==='POST'){try{const b=await request.json();const message=clean(b.message);if(!message)return json({error:'Message required'},400);const sensitive=/\b(?:pin|password|account number|id number|identity number|bank details)\b/i;if(sensitive.test(message))return json({response:'For your security, please do not share identity numbers, banking credentials, account or policy numbers here. I can still help with a general financial-planning question.',intent:'general'});const out=await env.AI.run('@cf/meta/llama-3.2-3b-instruct',{messages:[{role:'system',content:SYSTEM},{role:'user',content:message}],max_tokens:220,temperature:.35});return json({response:out.response||'An associate can help you explore that further.',intent:intentFor(message)});}catch(e){return json({error:'AI unavailable'},503)}}
if(u.pathname==='/api/lead'&&request.method==='POST'){try{const b=await request.json();const lead={id:crypto.randomUUID(),created_at:new Date().toISOString(),name:clean(b.name,100),phone:clean(b.phone,40),email:clean(b.email,160),associate:clean(b.associate,100),interest:clean(b.interest,100),preferred_date:clean(b.preferred_date,20),preferred_time:clean(b.preferred_time,20),contact_method:clean(b.preferred_contact_method,30),message:clean(b.message,1500),source:clean(b.source,50)};if(!lead.name||!lead.phone||!lead.email||!lead.associate||!lead.interest||!lead.message)return json({error:'Required fields missing'},400);if(!/^\S+@\S+\.\S+$/.test(lead.email))return json({error:'Invalid email'},400);await env.DB.prepare(`INSERT INTO leads (id,created_at,name,phone,email,associate,interest,preferred_date,preferred_time,contact_method,message,source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(...Object.values(lead)).run();return json({ok:true});}catch(e){return json({error:'Unable to save enquiry'},500)}}
return env.ASSETS.fetch(request)}};
